### ISSUE TITLE
Updating outdated packages

### ISSUE THREAD

**Issue by readeral** [philcon93/Theme-Starter-Kit#12]
Hey Phil,

Is there any harm in updating outdated dependencies on a newly generated theme? For example, a clean new theme, pulling in Skeletal, comes with ntheme 1.7.0, but you've released 1.8.1 (which is what I have installed globally) - does it make sense for me to update what is required by Skeletal to 1.8.1? Or will it break the build process?

**Comment by philcon93** [comment]
Yo @readeral, 

It should be all good to update your theme to have a ntheme version `1.8.1`, there isn't any breaking changes, just the new feature of uncompressed compile theme:

- https://github.com/philcon93/Theme-Starter-Kit/releases/tag/1.8.0

It's on my to do list to update Skeletal's dependency. It just requires a bit of work ensuring ci pipelines are all good.

**Comment by readeral** [comment]
Thanks Phil
