### ISSUE TITLE
Generate theme netothemeinfo.txt file

### ISSUE THREAD

**Issue by philcon93** [philcon93/Theme-Starter-Kit#3]
The original compile script will loop through all the netothemeinfo.txt files in the theme and make themes off that. The generate theme script doesn't add a netothemeinfo.txt file so generated themes can't use this compile script yet.

**Comment by matt-downs** [comment]
Would you be happy to include an NPM module? I was going to push this module pretty soon:
https://github.com/matt-downs/neto-theme-compile

**Comment by philcon93** [comment]
You might want to recheck the repo @matt-downs, I placed in my uncommitted code and fleshed out the compile script. 

This particular issue is to see if the generated script should be making a netothemeinfo.txt file, as it's used in the current compile script and it is used for the theme store I believe.

**Comment by matt-downs** [comment]
Ahh okay so this is more of a build script issue then 👍
