### ISSUE TITLE
Ability to target specific version of Skeletal

### ISSUE THREAD

**Issue by matt-downs** [philcon93/Theme-Starter-Kit#6]
I think it would be a good idea if the theme compile script was changed so that it could target a fixed release of Skeletal? Eg you could specify a dependency of Skeletal v18.4.0 in your package.json

This would smooth the release of breaking changes in Skeletal, ensuring that the theme owner must manually upgrade the version of Skeletal the theme is compiled against. When breaking changes are released as a newer Skeletal version, the outdated theme will continue to compile correctly against the older version of Skeletal until it is manually upgraded by the theme developer.

**Comment by philcon93** [comment]
https://github.com/philcon93/Theme-Starter-Kit/releases/tag/1.6.0 ;)

I'm going to be updating it when a theme in generated, the branch you generate from will be added to the generated theme's package.json. Then the compile script will check this value so it compile against the correct branch.
